### ISSUE TITLE
Importing browser polyfill does not work in IE8

### ISSUE THREAD

**Issue by Serabe** [6to5/ember-cli-6to5#11]
Browser polyfill makes our app crash in IE8.

**Comment by stefanpenner** [comment]
IE8 is es3

**Comment by Serabe** [comment]
Yes, but shouldn’t it be passed through the ES3 Safe Filter?

On 26 Jan 2015 at 16:16:08, Stefan Penner (notifications@github.com) wrote:

IE8 is es3

**Comment by stefanpenner** [comment]
> Yes, but shouldn’t it be passed through the ES3 Safe Filter?

the ES3 safe filter only transforms property names that are valid ES5+ but not es3.

```js
promise.catch(function() {});
```

becomes

**Comment by stefanpenner** [comment]
Additionally, we do not yet pull in the polyfil https://github.com/6to5/ember-cli-6to5/pull/6

**Comment by Serabe** [comment]
Ok, thanks.

**Comment by stefanpenner** [comment]
I am curious, can you share some stack trace or.. ?
