### ISSUE TITLE
Not working with addon

### ISSUE THREAD

**Issue by jclem** [6to5/ember-cli-6to5#13]
With a new add-on generated from Ember CLI v0.1.12, simply running `npm install --save-dev ember-cli-6to5` as the readme states does not run the add-on code through 6to5. Is there an extra step for Ember CLI add-ons?

**Comment by stefanpenner** [comment]
issue with ember-cli addons

**Comment by jclem** [comment]
Yeah, just saw that (https://github.com/ember-cli/ember-cli/issues/2354). Bummer.

**Comment by jclem** [comment]
@stefanpenner FWIW, updating the readme with this info might be useful. I spent about 20 minutes thinking I was doing something wrong before I opened this.

**Comment by stefanpenner** [comment]
@jclem its possible, but a-bit tricky. I have this working in my app, by overriding compileAddon in my add-on.

Something like: 
![screen shot 2015-02-04 at 3 21 48 pm](https://cloud.githubusercontent.com/assets/1377/6048891/ae03f7ba-ac81-11e4-9c4e-ad6dea128f30.png)

**Comment by jclem** [comment]
Thanks, @stefanpenner I'll try that out in the meantime.

**Comment by stefanpenner** [comment]
> Thanks, @stefanpenner I'll try that out in the meantime.

you do so at your own risk ;)

**Comment by stefanpenner** [comment]
@lukemelia's work will allow deeply nested add ons to correctly attach their own filters and transpilers. It will be nice :)

**Comment by lukemelia** [comment]
That PR is getting close. @jclem if you want to help out, you could help with once of the outstanding tasks in the checklist.

**Comment by jclem** [comment]
@lukemelia I've never looked into Ember CLI's internals at all, actually :\ I'll take a look at it if I have some time. If not, I'm perfectly happy being patient :)

**Comment by aceofspades** [comment]
Can anybody confirm this is still pending as of 0.2.0?

**Comment by rwjblue** [comment]
@aceofspades - using babel in an addon works properly under ember-cli 0.2.0

**Comment by aceofspades** [comment]
@rwjblue Thanks for confirming, oddly modules in addon are definitely not getting transpiled. Assuming it should be automatic w/default config... Will dig further.

**Comment by stefanpenner** [comment]
Modules don't get compiled with babel we use Esperanto for thst

**Comment by aceofspades** [comment]
@stefanpenner Are you saying something different happens for addons? I'm finding the various steps and recent changes confusing, not sure how up to date the docs are

**Comment by stefanpenner** [comment]
> @stefanpenner Are you saying something different happens for addons? I'm finding the various steps and recent changes confusing, not sure how up to date the docs are

nope, everything should be the same.

**Comment by aceofspades** [comment]
@stefanpenner Just create issue per fail https://github.com/ember-cli/ember-cli/issues/3556
